# Generated by Django 2.2.7 on 2019-11-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20191105_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hostel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
