# Generated by Django 2.2.7 on 2019-11-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='i_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
