# Generated by Django 2.2.7 on 2019-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_i_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hostel',
            field=models.CharField(blank=True, default='BH-2', max_length=10, null=True),
        ),
    ]
